SELECT
PROJECT_ID,
AVG(DATEDIFF(month, START_DATE, FINISH_DATE)) * SUM(SALARY) AS PRICE
FROM PROJECT_WORKER
JOIN PROJECT ON PROJECT.ID = PROJECT_WORKER.PROJECT_ID
JOIN WORKER ON WORKER.ID = PROJECT_WORKER.WORKER_ID
GROUP BY PROJECT_ID