CREATE TABLE IF NOT EXISTS worker(
	ID INT  PRIMARY KEY,
	NAME VARCHAR(1000) NOT NULL,
	BIRTHDAY DATE CHECK (BIRTHDAY > '1900-01-01'),
	LEVEL VARCHAR(10) NOT NULL CHECK
	(LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
	SALARY INT CHECK (SALARY > 100 AND SALARY < 100000)
);

CREATE TABLE IF NOT EXISTS client(
	ID INT  PRIMARY KEY,
	NAME VARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS project(
	ID INT  PRIMARY KEY,
	CLIENT_ID INT,
	START_DATE DATE CHECK (START_DATE > '1900-01-01'),
	FINISH_DATE DATE CHECK (FINISH_DATE > '1900-01-01')
);

CREATE TABLE IF NOT EXISTS project_worker(
	PROJECT_ID INT  REFERENCES project(ID),
	WORKER_ID INT REFERENCES worker(ID),
	PRIMARY KEY (project_id, worker_id)
);
